This adds the ability for someone to query by account id as well as username
henhouse/fortnite-go pull request #2
Opened 2018-11-28 18:08 UTC by Fyb3roptik

Sometimes people change their Epic Username and it will cause issues. If you can record their account id and use that instead, then that is the better option

2018-12-07 20:28 UTC, henhouse requested changes
Hey, thanks for the PR! Sorry that it took me a few days to get around to reviewing it. I made a few comments on the changes for you to take a look at when you get the chance.

2018-12-07 20:28 UTC, henhouse commented on epic.go
> +	if len(*sr) == 0 {
You already make this check in the `QueryPlayerById`, so this block could be removed.

2018-12-07 20:28 UTC, henhouse commented on epic.go
> +func (s *Session) QueryPlayer(name string, platform string, account_id string) (*Player, error) {
The Go standard is to use camelCase for variable names, so consider changing this to `accountId` or `accountID`. Additionally, let's keep `platform` as the last parameter so that the order feels right. Additionally, feel free to split this into two functions such as `QueryPlayer` and `QueryPlayerByAccountID` as this is also the common Go way.

2018-12-11 19:22 UTC, Fyb3roptik commented
I will make those changes. Epic as of today changed their oauth too, so I am working on that fix as well

2018-12-12 06:16 UTC, Fyb3roptik commented on epic.go
> +	if len(*sr) == 0 {
Fixed in latest commit

2018-12-12 06:16 UTC, Fyb3roptik commented on epic.go
> +func (s *Session) QueryPlayer(name string, platform string, account_id string) (*Player, error) {
Fixed in latest commit

2018-12-12 06:17 UTC, Fyb3roptik commented
I have pushed the fixes for these. Also new Launcher token should be:

```
MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=
```

2018-12-12 08:56 UTC, henhouse approved these changes

2018-12-12 08:56 UTC, henhouse commented
Looks good!

2018-12-12 08:57 UTC, merged